/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DbConfigurationDialog.java
 *
 * Created on 2011-12-01, 17:44:14
 */
package dbmigrate.gui;
import java.awt.Dimension;

import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;
import javax.swing.GroupLayout;
import javax.swing.JButton;

import dbmigrate.model.db.DbConnector;

/**
 *
 * @author zyxist
 */
public class DbConfigurationDialog extends javax.swing.JDialog
{
	public DbConnector getConnector() {
		return connector;
	}

	public void setConnector(DbConnector connector) {
		this.connector = connector;
	}

	private DbConnector connector;
	private JTextField hostnameText;
	private JTextField usernameText;
	private JTextField passwordText;
	private JTextField databaseText;

	/** Creates new form DbConfigurationDialog */
	public DbConfigurationDialog(java.awt.Frame parent, boolean modal)
	{
		super(parent, true);
		setResizable(false);
		setPreferredSize(new Dimension(500, 200));
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        JLabel lblHostname = new JLabel("Hostname");
        lblHostname.setBounds(115, 30, 72, 15);
        
        JLabel lblUsername = new JLabel("Username");
        lblUsername.setBounds(115, 55, 72, 15);
        
        JLabel lblPassword = new JLabel("Password");
        lblPassword.setBounds(115, 80, 70, 15);
        
        JLabel lblDatabase = new JLabel("Database");
        lblDatabase.setBounds(118, 105, 69, 15);
        
        hostnameText = new JTextField();
        hostnameText.setBounds(218, 30, 114, 19);
        hostnameText.setColumns(10);
        
        usernameText = new JTextField();
        usernameText.setBounds(218, 55, 114, 19);
        usernameText.setColumns(10);
        
        passwordText = new JTextField();
        passwordText.setBounds(218, 80, 114, 19);
        passwordText.setColumns(10);
        
        databaseText = new JTextField();
        databaseText.setBounds(218, 105, 114, 19);
        databaseText.setColumns(10);
        getContentPane().setLayout(null);
        getContentPane().add(lblHostname);
        getContentPane().add(hostnameText);
        getContentPane().add(lblPassword);
        getContentPane().add(lblUsername);
        getContentPane().add(lblDatabase);
        getContentPane().add(databaseText);
        getContentPane().add(passwordText);
        getContentPane().add(usernameText);
        
        JButton btnNewButton = new JButton("Ok");
        btnNewButton.setBounds(218, 136, 117, 25);
        getContentPane().add(btnNewButton);
        
        JButton btnNewButton_1 = new JButton("Cancel");
        btnNewButton_1.setBounds(347, 136, 117, 25);
        getContentPane().add(btnNewButton_1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(DbConfigurationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(DbConfigurationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(DbConfigurationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(DbConfigurationDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable()
		{

			public void run()
			{
				DbConfigurationDialog dialog = new DbConfigurationDialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter()
				{

					@Override
					public void windowClosing(java.awt.event.WindowEvent e)
					{
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
}
